
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "./components/MainHeader";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mic-Ecom App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain />
        {children}
        <Footer />
        </body>
    </html>
  );
}
